#!/usr/bin/env python3
from __future__ import unicode_literals
from pytracker import StoryList, Story
import sys
import csv
if len(sys.argv) < 2:
    print("usage: {} [inputfile.json]\nexample: {} inputfile.json".format(sys.argv[0],sys.argv[0]))
    sys.exit(1)

filename = sys.argv[1]
stories = []

def ImportFromCsvFile( csvfilename):
    """Imports from the CSV file that is generated by PivotalTracker"""
    stories = []
    with open(csvfilename, 'r') as content_file:
        delimiter=','
        quotechar='"'
        if sys.version_info[0] == 2: #python2
            delimiter = delimiter.encode("ascii")
            quotechar = quotechar.encode("ascii")

        reader = csv.reader(content_file, delimiter=delimiter, quotechar=quotechar)
        headerrow = None
        for row in reader:
            if headerrow is None:
                headerrow = row
                continue
            for element in row:
                if element != None:
                    if "cottco" in element.lower():
                        story = Story.FromCsv(row)
                        print(story.story_id)
                        stories.append(story)
    return stories

stories = ImportFromCsvFile(filename)

print("Loaded {} stories from {}".format(len(stories), filename))
